greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    migrate-at-start: true

