greeting:
  message: "hello"

users:
  default:
    username: admin
    password: admin

quarkus:
  http:
    auth:
      basic: true
  swagger-ui:
    always-include: true
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    migrate-at-start: true

